---
# miniconda package dependencies
miniconda_package_dependencies:
  - bzip2

# main miniconda download server
miniconda_mirror: "https://repo.continuum.io/miniconda"

# version of python (2|3)
miniconda_python_ver: 3

# miniconda version
miniconda_ver: "4.5.12"

# miniconda checksums
miniconda_checksums:
  Miniconda2-4.5.12-Linux-x86_64.sh: "md5:4be03f925e992a8eda03758b72a77298"
  Miniconda3-4.5.12-Linux-x86_64.sh: "md5:866ae9dff53ad0874e1d1a60b1ad1ef8"
  Miniconda2-4.5.11-Linux-x86_64.sh: "md5:458324438b7b0e5afcc272b63d44195d"
  Miniconda3-4.5.11-Linux-x86_64.sh: "md5:e1045ee415162f944b6aebfe560b8fee"
  Miniconda2-4.5.4-Linux-x86_64.sh: "md5:8a1c02f6941d8778f8afad7328265cf5"
  Miniconda3-4.5.4-Linux-x86_64.sh: "md5:a946ea1d0c4a642ddf0c3a26a18bb16d"

# miniconda installer info
miniconda_name: "Miniconda{{ miniconda_python_ver }}-{{ miniconda_ver }}-Linux-x86_64"
miniconda_installer_sh: "{{ miniconda_name }}.sh"
miniconda_installer_url: "{{ miniconda_mirror }}/{{ miniconda_installer_sh }}"
miniconda_checksum: "{{ miniconda_checksums[miniconda_installer_sh] }}"

# when downloading the miniconda binary it might take a while
miniconda_timeout_seconds: 600

# where to install miniconda
miniconda_parent_dir: /opt
miniconda_etc_profile: /etc/profile.d
miniconda_dir: "{{ miniconda_parent_dir }}/miniconda"
miniconda_etc_profile_conda: "{{ miniconda_dir }}/etc/profile.d/conda"
miniconda_conda_bin: "{{ miniconda_dir }}/bin/conda"

# run update on base packages after install?
miniconda_pkg_update: true
...
