---
- dcb --upstreamgroup andrewrothstein --upstreamapp ansible-anaconda --snippet from.j2
  ansible-test-role.j2 --pullall --writeall --buildall --pushall --alltags ${OS}
- dcb --upstreamgroup andrewrothstein --upstreamapp ansible-miniconda --targetapp
  ansible-conda-env-miniconda --snippet from.j2 ansible-test-role.j2 --pullall --writeall
  --buildall --pushall --alltags ${OS}
